
# PYTHON


In [ ]:

Write a Python program to check whether a number is even or odd using if-else.


In [1]:

# Python program to check if a number is even or odd

# Get input from the user
number = int(input("Enter a number: "))

# Check if the number is even or odd using if-else
if number % 2 == 0:
    print(f"{number} is even.")
else:
    print(f"{number} is odd.")


Enter a number:  2


2 is even.


In [2]:

# Print numbers from 10 to 1 in reverse using a for loop
for i in range(10, 0, -1):
    print(i)


10
9
8
7
6
5
4
3
2
1


In [4]:

# While loop that continues until the user enters 0
number = None

while number != 0:
    number = int(input("Enter a number (0 to stop): "))
    print(f"You entered: {number}")

print("Loop ended. You entered 0.")


Enter a number (0 to stop):  3


You entered: 3


Enter a number (0 to stop):  4


You entered: 4


Enter a number (0 to stop):  0


You entered: 0
Loop ended. You entered 0.


In [5]:

# Function to return the sum of two numbers
def add_numbers(a, b):
    return a + b

# Example usage
result = add_numbers(5, 7)
print("The sum is:", result)



The sum is: 12


In [6]:

print(list(map(lambda x: x*x, [1, 2, 3])))


[1, 4, 9]


In [7]:

# Sample list of numbers
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use filter to get even numbers
even_numbers = list(filter(lambda x: x % 2 == 0, numbers))

# Print the result
print("Even numbers:", even_numbers)


Even numbers: [2, 4, 6, 8, 10]


In [ ]:

Explain the purpose of the else block in a try-except-else construct.


In [ ]:

try:
    # Code that might raise an exception
except SomeException:
    # Code that runs if an exception occurs
else:
    # Code that runs if no exception occurs


In [10]:

# Try-except block to handle division by zero
try:
    numerator = int(input("Enter the numerator: "))
    denominator = int(input("Enter the denominator: "))
    result = numerator / denominator
    print("Result:", result)
except ZeroDivisionError:
    print("Error: Division by zero is not allowed.")


Enter the numerator:  3
Enter the denominator:  5


Result: 0.6


In [11]:

print((lambda x, y: x + y)(5, 3))


8


In [12]:

# Define the Dog class
class Dog:
    def __init__(self, name, breed):
        self.name = name
        self.breed = breed

    def bark(self):
        print(f"{self.name} says: Woof!")

# Example usage
my_dog = Dog("Buddy", "Golden Retriever")
print(f"My dog's name is {my_dog.name} and breed is {my_dog.breed}.")
my_dog.bark()


My dog's name is Buddy and breed is Golden Retriever.
Buddy says: Woof!


In [13]:

class Dog:
    def __init__(self, name, breed):
        self.name = name
        self.breed = breed

    def bark(self):
        print(f"{self.name} says: Woof!")

# Create two Dog objects
dog1 = Dog("Max", "Labrador")
dog2 = Dog("Bella", "German Shepherd")

print(f"Dog 1: {dog1.name}, Breed: {dog1.breed}")
dog1.bark()

print(f"Dog 2: {dog2.name}, Breed: {dog2.breed}")
dog2.bark()


Dog 1: Max, Breed: Labrador
Max says: Woof!
Dog 2: Bella, Breed: German Shepherd
Bella says: Woof!


In [14]:

class Dog:
    species = "Canis familiaris"  

    def __init__(self, name, breed):
        self.name = name  
        self.breed = breed  

# Create two Dog objects
dog1 = Dog("Buddy", "Golden Retriever")
dog2 = Dog("Max", "Labrador")

# Accessing class variable via class name and instance
print(Dog.species)  
print(dog1.species)  
print(dog2.species)  


Canis familiaris
Canis familiaris
Canis familiaris


In [15]:

print("apple" if 5 > 3 else "banana")


apple


In [17]:


def square_list(numbers):
    return [x**2 for x in numbers]

# Example usage
numbers = [1, 2, 3, 4, 5]
squared_numbers = square_list(numbers)
print(squared_numbers)  


[1, 4, 9, 16, 25]


In [ ]:

map(function, iterable)


In [20]:

numbers = [1, 2, 3, 4, 5]
result = map(lambda x: x**2, numbers)

# Convert map object to list to see the result
print(list(result))  


[1, 4, 9, 16, 25]



# NUMPY


In [21]:

[[2, 9, 3],
 [5, 8, 4],
 [3, 7, 9]]


[[2, 9, 3], [5, 8, 4], [3, 7, 9]]

In [22]:

[[2, 0, 8],
 [5, 1, 8]]



[[2, 0, 8], [5, 1, 8]]

In [ ]:

Combine two 3x3 matrices using np.concatenate along axis 0 and axis 1.


In [23]:

import numpy as np

# Create two 3x3 matrices
matrix1 = np.random.randint(0, 10, (3, 3))
matrix2 = np.random.randint(0, 10, (3, 3))

# Concatenate along axis 0 (vertically)
concat_axis0 = np.concatenate((matrix1, matrix2), axis=0)

# Concatenate along axis 1 (horizontally)
concat_axis1 = np.concatenate((matrix1, matrix2), axis=1)

print("Concatenated along axis 0 (vertically):")
print(concat_axis0)

print("Concatenated along axis 1 (horizontally):")
print(concat_axis1)


Concatenated along axis 0 (vertically):
[[4 3 6]
 [7 0 7]
 [4 7 5]
 [9 1 5]
 [7 5 6]
 [8 7 8]]
Concatenated along axis 1 (horizontally):
[[4 3 6 9 1 5]
 [7 0 7 7 5 6]
 [4 7 5 8 7 8]]


In [24]:

import numpy as np

# Create two 3x3 matrices
matrix1 = np.random.randint(0, 10, (3, 3))
matrix2 = np.random.randint(0, 10, (3, 3))

# Element-wise addition
addition_result = matrix1 + matrix2

# Element-wise subtraction
subtraction_result = matrix1 - matrix2

# Element-wise multiplication
multiplication_result = matrix1 * matrix2

# Print results
print("Matrix 1:")
print(matrix1)
print("\nMatrix 2:")
print(matrix2)

print("\nElement-wise Addition:")
print(addition_result)

print("\nElement-wise Subtraction:")
print(subtraction_result)

print("\nElement-wise Multiplication:")
print(multiplication_result)



Matrix 1:
[[0 7 9]
 [5 0 7]
 [2 0 0]]

Matrix 2:
[[2 6 8]
 [2 3 3]
 [2 1 4]]

Element-wise Addition:
[[ 2 13 17]
 [ 7  3 10]
 [ 4  1  4]]

Element-wise Subtraction:
[[-2  1  1]
 [ 3 -3  4]
 [ 0 -1 -4]]

Element-wise Multiplication:
[[ 0 42 72]
 [10  0 21]
 [ 4  0  0]]


In [ ]:

Demonstrate broadcasting by adding a 1D array to a 2D array.


In [25]:

import numpy as np

# Create a 2D array (3x3)
array_2d = np.random.randint(0, 10, (3, 3))

# Create a 1D array (size 3)
array_1d = np.array([1, 2, 3])

# Add the 1D array to the 2D array using broadcasting
result = array_2d + array_1d

print("2D Array:")
print(array_2d)

print("\n1D Array:")
print(array_1d)

print("\nResult after broadcasting and addition:")
print(result)



2D Array:
[[8 4 6]
 [7 6 7]
 [5 8 2]]

1D Array:
[1 2 3]

Result after broadcasting and addition:
[[ 9  6  9]
 [ 8  8 10]
 [ 6 10  5]]


In [26]:

import numpy as np

# Create a 3x3 matrix with random integers
matrix = np.random.randint(0, 10, (3, 3))

# Use np.clip to limit the values between 2 and 8
clipped_matrix = np.clip(matrix, 2, 8)

print("Original Matrix:")
print(matrix)

print("\nClipped Matrix (values between 2 and 8):")
print(clipped_matrix)


Original Matrix:
[[6 8 5]
 [1 4 2]
 [9 2 9]]

Clipped Matrix (values between 2 and 8):
[[6 8 5]
 [2 4 2]
 [8 2 8]]


In [27]:

import numpy as np

# Create an array of floating-point numbers
array = np.array([1.2, 2.5, 3.8])

# Use np.ceil to round up the values to the nearest integer
ceiled_array = np.ceil(array)

print("Ceiled Array:", ceiled_array)


Ceiled Array: [2. 3. 4.]


In [28]:

import numpy as np

# Create an array with random integers
array = np.random.randint(0, 10, (3, 3))

# Use np.where to replace all elements greater than 5 with 100
modified_array = np.where(array > 5, 100, array)

print("Original Array:")
print(array)

print("\nModified Array (elements greater than 5 replaced with 100):")
print(modified_array)


Original Array:
[[4 6 6]
 [4 9 3]
 [1 8 8]]

Modified Array (elements greater than 5 replaced with 100):
[[  4 100 100]
 [  4 100   3]
 [  1 100 100]]
